### ISSUE TITLE
Space Weather

### ISSUE THREAD

**Issue by bloudman648** [AresValley/Artemis#60] opened 2024-10-10 18:04 UTC
Drap isn't available.
No data.

Drap is the category, where you can see degraded frequency absorbtion.

**Comment by AresValley** [comment] 2024-10-10 18:36
@bloudman648 I checked right now and I'm not able to reproduce the problem. The 18:25/18:30/18:35 UTC reports have been generated along the drap and aurora graph.

![Screenshot 2024-10-10 203214](https://github.com/user-attachments/assets/5f14e11c-640b-45c8-855c-ac975a8cc0b3)
![Screenshot 2024-10-10 203150](https://github.com/user-attachments/assets/ce6b3898-204b-4f14-9557-718fe13ad2ff)

My guess is that the problem perhaps was generated by a lack of updated data from NOAA

**Comment by AresValley** [comment] 2024-10-10 18:37
I'm not closing the issue so I can investigate a little bit more in detail

**Comment by AresValley** [comment] 2024-10-10 18:58
Yep, the 18:40 UTC report shows the problem you described and I was able to locate and fix the bug. The new version of Poseidon (the engine that produces space weather reports) is already in production without any further action required from you side.
Thanks @bloudman648 for your report!

**Closed by AresValley** 2024-10-10 18:58 UTC
Labels: bug

**Comment by bloudman648** [comment] 2024-10-10 19:08
now 'spaceweather' crashes the whole app.
tried re-installing but didnt worked.

**Comment by AresValley** [comment] 2024-10-10 19:13
Awesome, thanks for the feedback! ;)
Yes, indeed (about the storm).

If you still have some issues, feel free to reopen this issue or open a new one.
